# Configuration des API AgriSmart
huggingface.key=hf_CeWYSMXfAUBaxDXoGLFCDmjbPEflxFQXr
gemini.key=AIzaSyCLU3zWJjKhCkPpFA1j41KIw-RffCINONk
plantid.key=qcL7ft5XRbTUJz8vxafCi9i7njTKQUsFvJl8eDW89swzt4XKGy
GOOGLE_CALENDAR_API_KEY=AIzaSyCELVRV52-cqqJLwgGABnkYmTxsBXDbCKY
